spring:
  application:
    name: gafarin-wan-api

  datasource:
    url: jdbc:postgresql://localhost:5432/gafargan_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
